### PR TITLE
Use md5 for fingerprint hash.

### PR DESCRIPTION
**Pull request by hodgestar**
This replaces the Python hash used for the fingerprint with an md5 hash and removes the need to specify `PYTHONHASHSEED=0` when calling `mypy-gitlab-code-quality`.

Note that this change will cause a one break in the continuity of fingerprints for existing users. I don't know how much of a concern this is -- the Python `hash` was never guaranteed to return any stable value, and indeed varies across architectures (32-bit vs 64-bit) and has varied in the past across Python versions.

P.S. There is also a question of whether just `line` is a sufficient or the correct input to the fingerprint. Should any other issue information be included?

### CODE REVIEW

**Comment by OokamiTheLord** [comment]
I believe you should also bump version to `1.1.0` (bump minor since it's more than a bug fix)

**Comment by soul-catcher** [comment]
Thank you for opening pull request!
Indeed, using the built-in hash function was a bad idea.
Can you also delete setting of environment variable in yaml example in README?

As for including additional information to fingerprint, I have no ideas. If you have, feel free to suggest.

**Comment by soul-catcher** [comment]
Thank you for fixing linters warnings

I will push changes to PyPi in next 30 minutes

**Comment by hodgestar** [comment]
Pleasure, and thank you for reviewing.

**Pull request merged**
